Repository uhafner/codingstyle, pull requests merged in 2022-05, with the labels that each got.

#554 Add a new class that can extract files from a classloader classpath
  pom.xml
  src/main/java/edu/hm/hafner/util/ResourceExtractor.java
  src/test/java/edu/hm/hafner/util/ResourceExtractorTest.java
Labels: feature

#552 Update RevApi Config
  pom.xml
Labels: internal

#558 Add tests that verify some ArchUnit rules
  src/test/java/edu/hm/hafner/util/ArchitectureRulesTest.java
  src/test/java/edu/hm/hafner/util/ArchitectureTest.java
Labels: tests
