Repository uhafner/codingstyle, pull requests merged in 2023-11, with the labels that each got.

#851 Override `equals` for `FilteredLog`
  pom.xml
  src/main/java/edu/hm/hafner/util/FilteredLog.java
  src/test/java/edu/hm/hafner/util/FilteredLogTest.java
Labels: enhancement

#855 Add english version of doc/Arbeiten-mit-GitHub.md
  doc/Working-with-Github.md
Labels: documentation

#859 Use 2.0.0 autograding
  .github/workflows/autograding.yml
  .github/workflows/coverage.yml
  .github/workflows/reporting.yml
Labels: internal

#861 Exclude CT_CONSTRUCTOR_THROW SpotBugs warning
  etc/spotbugs-exclusion-filter.xml
  src/main/java/edu/hm/hafner/util/ResourceExtractor.java
Labels: internal

#862 Deactivate LiteralsFirstInComparisons PMD rule.
  etc/pmd-configuration.xml
Labels: internal

#867 Enable error prone warnings
  .github/workflows/reporting.yml
Labels: internal
